151 define help function
PythonPredictions/cobra pull request #167
Opened 2023-04-24 11:35 UTC by patrickleonardy

# Define help function

[#151]

## Changes made

- remove the previous implementation that prints while importing 
- add the text in the __init__.py file such that this is printed when calling `help(cobra)`

## Linked issues

Resolves #151

2023-04-28 12:59 UTC, ZlaTanskY requested changes, later dismissed

2023-04-28 12:59 UTC, ZlaTanskY commented on cobra/__init__.py
> +https://github.com/PythonPredictions/cobra/blob/develop/Cobra.pdf
The link is not working, as the pdf file is not present.
I'm also not a fan of adding a presentation to the repository, as this is a living document and will change over time, which means the pdf will eventually be outdated.

2023-05-12 13:27 UTC, patrickleonardy commented on cobra/__init__.py
> +https://github.com/PythonPredictions/cobra/blob/develop/Cobra.pdf
I will then just keep the presentation out of it. One should be able to get all the necessary information by having a look at our documentation and wiki.

2023-05-12 14:50 UTC, ZlaTanskY approved these changes

2023-05-12 14:51 UTC, merged